version: "3.9"
services:
  webapp:
    restart: always
    depends_on:
      - database
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - webapp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  pgdata:
